RSpec/MultipleExpectations:
  Max: 16

RSpec/ExampleLength:
  Max: 50

RSpec/MessageExpectation:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/Pending:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false
