Migration/DepartmentName:
  Enabled: false

# Metrics ----------------------------------------------------------------------

Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

# Bundler ----------------------------------------------------------------------

Bundler/OrderedGems:
  Enabled: false

Bundler/GemComment:
  Enabled: false

# Gemspec ----------------------------------------------------------------------

Gemspec/OrderedDependencies:
  Enabled: false

# Style ------------------------------------------------------------------------

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/WordArray:
  MinSize: 2

Style/RegexpLiteral:
  EnforcedStyle: mixed

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Proc:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/CollectionMethods:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/PreferredHashMethods:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/ReturnNil:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/Next:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FloatDivision:
  Enabled: false

# Naming -----------------------------------------------------------------------

Naming/PredicateName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Naming/RescuedExceptionsVariableName:
  PreferredName: exception

Naming/FileName:
  Exclude:
    - tmp/*
    - bin/*
    - script/*

Naming/AccessorMethodName:
  Enabled: false

# Layout -----------------------------------------------------------------------

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundArguments:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Layout/FirstMethodParameterLineBreak:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/SpaceInsideReferenceBrackets:
  Enabled: false

Layout/HashAlignment:
  Enabled: false
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

# Lint -------------------------------------------------------------------------

Lint/EmptyWhen:
  Enabled: false

Lint/UnusedBlockArgument:
  AllowUnusedKeywordArguments: true

Lint/UnusedMethodArgument:
  AllowUnusedKeywordArguments: true

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/DisjunctiveAssignmentInConstructor:
  Enabled: false
